# Generated by Django 5.2.9 on 2026-01-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['priority_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['passage_order', 'created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='criterion',
                    name='priority_order',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='team',
                    name='email',
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AddField(
                    model_name='team',
                    name='generated_email',
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AddField(
                    model_name='team',
                    name='has_logged_in',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='team',
                    name='imported_from',
                    field=models.CharField(default='manual', max_length=50),
                ),
                migrations.AddField(
                    model_name='team',
                    name='passage_order',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='team',
                    name='passage_time',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='team',
                    name='password',
                    field=models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('jury', 'Jury'), ('team', 'Team')], default='jury', max_length=10),
        ),
        migrations.AddField(
            model_name='criterion',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='jury_api.event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='jury_api.event'),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='jury_api.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jury_api.event'),
        ),
    ]
