# Generated by Django 5.2.9 on 2026-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury_api', '0002_event_alter_criterion_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='criterion_comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='global_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
