# Generated by Django 5.2.9 on 2026-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury_api', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_presentations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='presentation_duration',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='presentation_start_time',
            field=models.CharField(blank=True, default='08:00', max_length=10, null=True),
        ),
    ]
