# Generated by Django 5.2.9 on 2026-02-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury_api', '0006_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='criterion',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='jury_api.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jury_api.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='jury_api.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='jury_api.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jury_api.event'),
            preserve_default=False,
        ),
    ]
