# Generated by Django 5.2.9 on 2026-02-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury_api', '0007_alter_message_options_alter_criterion_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='jury_api.event'),
        ),
    ]
